name: "mongoid_model_load_bug"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    command: sleep infinity

    environment:
      MONGODB_URL: "mongodb://mongo:27017/mongoid_model_load_bug_development"
    
    depends_on:
    - selenium
    - postgres
    - mongo

  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongoid_model_load_bug_development
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/mongoid_model_load_bug_development --quiet
      interval: 5s

volumes:
  postgres-data:
  mongo-data:
